const domElements = {
    oreCliStatus: document.getElementById('ore-cli-status'),
    startMinerBtn: document.getElementById('start-miner'),
    stopMinerBtn: document.getElementById('stop-miner'),
    minerForm: document.getElementById('miner-form'),
    feeTypeSelect: document.getElementById('fee-type'),
    staticFeeGroup: document.getElementById('static-fee-group'),
    dynamicFeeGroup: document.getElementById('dynamic-fee-group'),
    maxFeeCapGroup: document.getElementById('max-fee-cap-group'),
    profileList: document.getElementById('profile-list'),
    saveProfileBtn: document.getElementById('save-profile'),
    bestHashElement: document.getElementById('best-hash'),
    profileNameInput: document.getElementById('profile-name'),
    installCheckModal: document.getElementById('install-check-modal'),
    installCheckModalContent: document.getElementById('modal-content'),
    installCheckModalClose: document.querySelector('#install-check-modal .close'),
    logContent: document.getElementById('log-content'),
    avgDifficulty: document.getElementById('avg-difficulty'),
    showDifficultyDetailsBtn: document.getElementById('show-difficulty-details'),
    difficultyModal: document.getElementById('difficulty-modal'),
    oreCliError: document.getElementById('ore-cli-error'),
    transferButton: document.getElementById('transfer-button'),
    transferModal: document.getElementById('transfer-modal'),
    transferConfirmButton: document.getElementById('transfer-confirm-button'),
    transferClose: document.getElementById('transfer-close'),
    stakeButton: document.getElementById('stake-button'),
    stakeModal: document.getElementById('stake-modal'),
    stakeConfirmButton: document.getElementById('stake-confirm-button'),
    stakeClose: document.getElementById('stake-close'),
    claimButton: document.getElementById('claim-button'),
    claimModal: document.getElementById('claim-modal'),
    claimConfirmButton: document.getElementById('claim-confirm-button'),
    claimClose: document.getElementById('claim-close'),
    transferAddressInput: document.getElementById('transfer-address'),
    difficultyClose: document.querySelector('#difficulty-modal .close'),
    orePrice: document.getElementById('ore-price'), 
    oreBalance: document.getElementById('ore-balance'), 
};

module.exports = domElements;
